- model/src/main/java/com/lovely4k/backend/member/Member.java
> feat : member 엔티티 추가

- model/src/main/java/com/lovely4k/backend/couple/Couple.java
> feat : couple 엔티티 추가 [#5]

- model/src/main/java/com/lovely4k/backend/diary/Diary.java
- model/src/main/java/com/lovely4k/backend/diary/Photos.java
- model/src/main/java/com/lovely4k/backend/location/Category.java
- model/src/main/java/com/lovely4k/backend/location/Location.java
> feat : 다이어리 관련 entity 생성 [#7, #8]

- model/src/main/java/com/lovely4k/backend/question/Question.java
- model/src/main/java/com/lovely4k/backend/question/QuestionChoices.java
- model/src/main/java/com/lovely4k/backend/question/QuestionForm.java
> feat : question 관련 entity 생성 [#10, #11]

- api/src/main/resources/application-local.yaml
- api/src/main/resources/application.yaml
- api/src/main/resources/schema/schema.sql
- model/build.gradle
> chore : Profile별 yml파일 설정 [#15]

- api/src/main/java/com/lovely4k/backend/common/ApiResponse.java
- api/src/main/java/com/lovely4k/backend/common/GlobalExceptionHandler.java
- api/src/main/java/com/lovely4k/backend/common/ProblemDetailCreator.java
- api/src/main/java/com/lovely4k/backend/common/ValidationError.java
> feat : API 공통 응답 작성 [#17]

- api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
- api/src/test/java/com/lovely4k/docs/RestDocsSupport.java
> feat : 테스트 Support Class 작성

- api/src/main/java/com/lovely4k/backend/common/ApiResponse.java
- api/src/main/java/com/lovely4k/backend/common/GlobalExceptionHandler.java
- api/src/main/java/com/lovely4k/backend/common/ProblemDetailCreator.java
- api/src/main/java/com/lovely4k/backend/common/enumvalidator/EnumValue.java
- api/src/main/java/com/lovely4k/backend/common/enumvalidator/ValueOfEnumValidator.java
- api/src/main/java/com/lovely4k/backend/diary/controller/DiaryController.java
- api/src/main/java/com/lovely4k/backend/diary/controller/request/DiaryCreateRequest.java
- api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
- api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
- api/src/test/java/com/lovely4k/backend/diary/controller/DiaryControllerTest.java
- api/src/test/java/com/lovely4k/backend/diary/controller/MockDiaryCreateRequest.java
- api/src/test/java/com/lovely4k/docs/RestDocsSupport.java
- api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
- api/src/test/java/com/lovely4k/docs/diary/MockDiaryCreateRequest.java
- model/src/main/java/com/lovely4k/backend/ModelApplication.java
- model/src/test/java/com/lovely4k/backend/ModelApplicationTests.java
다이어리 생성 관련 api 문서화 및 Controller 테스트 검증 
---
없습니다. 
---
- Enum Type에 대해 검증을 할 수 있는 validator를 만들었습니다. 확인 부탁드려요 (@EnumValue)
- ApiResponse에서 리소스가 생성됐을 때를 대비해 `created` static method를 만들었습니다. 확인 부탁드립니다.
---
[ 테스트 완료 사항 ]
- API Docs 관련 테스트
- Controller 테스트 
---
> Feature diary create

- api/src/main/java/com/lovely4k/backend/common/ApiResponse.java
- api/src/main/java/com/lovely4k/backend/diary/controller/DiaryController.java
- api/src/main/java/com/lovely4k/backend/diary/controller/request/DiaryEditRequest.java
- api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryDetailResponse.java
- api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryListResponse.java
- api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
- api/src/test/java/com/lovely4k/docs/diary/MockDiaryEditRequest.java
RestDocs 문서 작성 
---
없습니다.
---
테스트코드 부분 관련해서만 봐주시면 좋을 것 같습니다. 
---
문서화 작업 완료 
---
> docs : diary 문서화 작업 진행 [#22]

- api/src/main/java/com/lovely4k/backend/common/ApiResponse.java
- api/src/main/java/com/lovely4k/backend/couple/controller/CoupleController.java
- api/src/main/java/com/lovely4k/backend/couple/controller/request/CoupleProfileEditRequest.java
- api/src/main/java/com/lovely4k/backend/couple/service/response/CoupleProfileGetResponse.java
- api/src/main/java/com/lovely4k/backend/member/controller/MemberController.java
- api/src/main/java/com/lovely4k/backend/member/controller/request/MemberProfileEditRequest.java
- api/src/main/java/com/lovely4k/backend/member/service/response/MemberProfileGetResponse.java
- api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
- api/src/test/java/com/lovely4k/docs/CoupleControllerDocsTest.java
- api/src/test/java/com/lovely4k/docs/MemberControllerDocsTest.java
- Restdoct 작성
---
---
---
- Restdoc 작성 완료하였습니다.
---
> docs : 커플, 프로필 API 명세서 작성 [#24]

- api/src/main/java/com/lovely4k/backend/common/ApiResponse.java
- api/src/main/java/com/lovely4k/backend/question/controller/QuestionController.java
- api/src/main/java/com/lovely4k/backend/question/controller/request/CreateQuestionFormRequest.java
- api/src/main/java/com/lovely4k/backend/question/service/QuestionService.java
- api/src/main/java/com/lovely4k/backend/question/service/response/CreateQuestionFormResponse.java
- api/src/main/java/com/lovely4k/backend/question/service/response/CreateQuestionResponse.java
- api/src/main/java/com/lovely4k/backend/question/service/response/DailyQuestionResponse.java
- api/src/main/java/com/lovely4k/backend/question/service/response/QuestionDetailsResponse.java
- api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
- api/src/test/java/com/lovely4k/docs/question/QuestionApiDocs.java
RestDocs 문서 작성
---
없습니다.
---
테스트코드 부분 관련해서만 봐주시면 좋을 것 같습니다.
---
---
문서화 작업 완료
> docs : question api restdocs 작성

- api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
- api/src/main/java/com/lovely4k/backend/member/controller/MemberController.java
- api/src/main/java/com/lovely4k/backend/member/service/MemberService.java
- api/src/main/java/com/lovely4k/backend/member/service/response/MemberProfileGetResponse.java
- api/src/main/resources/schema/schema.sql
- api/src/test/java/com/lovely4k/backend/ApiApplicationTests.java
- api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
- api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
- api/src/test/java/com/lovely4k/backend/member/controller/MemberControllerTest.java
- api/src/test/java/com/lovely4k/backend/member/service/MemberServiceTest.java
- api/src/test/java/com/lovely4k/docs/MemberControllerDocsTest.java
- model/src/main/java/com/lovely4k/backend/member/Member.java
- model/src/main/java/com/lovely4k/backend/member/repository/MemberRepository.java
- 회원 프로필 조회 controller, service 및 테스트 구현
- controller를 구현함에 있어서 restdocs 테스트 코드 수정
---
없습니다.
---
로직이 없는 단순 조회 기능을 구현하여서 전체적으로 한번 쓱 봐주시면 좋을것 같아요.
---
service, controller 테스트 완료
---
> feat : 회원 프로필 조회 기능 구현 [#29]

- api/src/main/java/com/lovely4k/backend/diary/controller/DiaryController.java
- api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
- api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
- api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
- model/src/main/java/com/lovely4k/backend/diary/Diary.java
- model/src/test/java/com/lovely4k/backend/diary/DiaryTest.java
유저가 다이어리를 삭제할 수 있게끔 기능 구현 
---
없습니다. 
---
DiaryController, DiaryService 
---
테스트를 완료했습니다.
---
> feat : 다이어리 삭제 기능 구현 [#46, #47]

- api/src/main/java/com/lovely4k/backend/couple/controller/CoupleController.java
- api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
- api/src/main/java/com/lovely4k/backend/couple/service/response/InvitationCodeCreateResponse.java
- api/src/main/resources/schema/schema.sql
- api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
- api/src/test/java/com/lovely4k/backend/couple/controller/CoupleControllerTest.java
- api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceTest.java
- api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
- model/src/main/java/com/lovely4k/backend/couple/Couple.java
- 초대 코드를 발급받아야 커플 등록이 가능.
- 추후 초대 코드 로직 적용
- 초대 보내는 사람이 무조건 남자로 해두었는데 로그인 기능 생성 후 성별 구분 로직 추가 예정
---
---
---
- 테스트 문제 없습니다.
---
> feat : 초대 코드 생성 기능 구현 [#50]

- api/src/main/java/com/lovely4k/backend/diary/controller/DiaryController.java
- api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
- api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryListResponse.java
- api/src/test/java/com/lovely4k/docs/RestDocsSupport.java
- api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
- model/build.gradle
- model/src/main/java/com/lovely4k/backend/diary/DiaryRepositoryAdapter.java
- model/src/main/java/com/lovely4k/backend/diary/QDiaryRepository.java
- model/src/main/java/com/lovely4k/backend/location/Category.java
- model/src/test/java/com/lovely4k/backend/IntegrationTestSupport.java
- model/src/test/java/com/lovely4k/backend/diary/QDiaryRepositoryTest.java
- model/src/test/java/com/lovely4k/backend/location/CategoryTest.java
다이어리 목록 조회 기능 구현
---
없습니다. 
---
Repository 영역을 Adapter 패턴으로 변경했습니다. 확인 부탁드려요.
---
테스트 완료
---
> feat : 다이어리 목록 조회 기능 구현 [#46, #56]

- api/src/main/java/com/lovely4k/backend/couple/controller/CoupleController.java
- api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
- api/src/test/java/com/lovely4k/backend/couple/controller/CoupleControllerTest.java
- api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceTest.java
- api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
- model/src/main/java/com/lovely4k/backend/couple/Couple.java
- model/src/main/java/com/lovely4k/backend/couple/repository/CoupleRepository.java
- 초대 코드를 통해 초대코드 발신자와 수신자가 커플이 등록됨.
---
없습니다.
---
---
전체 테스트 완료했습니다.
---
> feat : 초대코드를 통한 커플 등록 [#53]

- api/src/main/java/com/lovely4k/backend/couple/controller/CoupleController.java
- api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
- api/src/main/java/com/lovely4k/backend/couple/service/response/CoupleProfileGetResponse.java
- api/src/test/java/com/lovely4k/backend/couple/controller/CoupleControllerTest.java
- api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceTest.java
- api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
- 커플 프로필 조회 기능 구현
---
---
---
- 테스트 완료하였습니다.
---
> feat : 커플 프로필 조회 [#54]

- api/src/main/java/com/lovely4k/backend/couple/controller/CoupleController.java
- api/src/main/java/com/lovely4k/backend/couple/controller/request/CoupleProfileEditRequest.java
- api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
- api/src/main/java/com/lovely4k/backend/couple/service/request/CoupleProfileEditServiceRequest.java
- api/src/test/java/com/lovely4k/backend/couple/controller/CoupleControllerTest.java
- api/src/test/java/com/lovely4k/backend/couple/controller/request/TestCoupleProfileEditRequest.java
- api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceTest.java
- api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
- model/src/main/java/com/lovely4k/backend/couple/Couple.java
- model/src/main/java/com/lovely4k/backend/member/Member.java
- 커플 프로필 수정 기능 MVP구현
---
---
---
- 테스트 잘 돌아갑니다.
---
> feat : 커플 프로필 수정 [#55]

- api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
- 초대코드 API restdocs 작성하였습니다.
---
---
---
---
> docs : 초대코드 생성 API restdocs 작성

- api/src/test/java/com/lovely4k/backend/ApiApplicationTests.java
- build.gradle
- model/src/test/java/com/lovely4k/backend/ModelApplicationTests.java
- model/src/test/java/com/lovely4k/backend/question/QuestionChoicesTest.java
- model/src/test/java/com/lovely4k/backend/question/QuestionTest.java
---
---
---
- 모든 경우에 대해 테스트 하지 않아서 questions에 테스트를 추가했습니다
---
> test : question 도메인 테스트 추가

- api/src/main/java/com/lovely4k/backend/diary/controller/DiaryController.java
- api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
- api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryDetailResponse.java
- api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryListResponse.java
- api/src/main/java/com/lovely4k/backend/diary/service/response/PhotoListResponse.java
- api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
- api/src/test/java/com/lovely4k/backend/diary/service/response/photoListResponseTest.java
- api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
- model/src/main/java/com/lovely4k/backend/diary/DiaryRepositoryAdapter.java
- model/src/main/java/com/lovely4k/backend/location/Category.java
- model/src/test/java/com/lovely4k/backend/diary/DiaryRepositoryAdapterTest.java
- model/src/test/java/com/lovely4k/backend/diary/DiaryTest.java
- model/src/test/java/com/lovely4k/backend/diary/PhotosTest.java
- model/src/test/java/com/lovely4k/backend/location/CategoryTest.java
새로 작성한 메서드 중 미확인 된 부분 테스트 추가 
---
없습니다. 
---
테스트 케이스가 적절한지 봐주세요 🙏
---
미구현 테스트 완료 
---
> test : diary 추가 테스트 작성

- api/src/main/java/com/lovely4k/backend/diary/controller/DiaryController.java
- api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
- api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
- api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
일부 API -> request parmeter memberId -> coupleId 로 변경
---
없습니다.
---
memberId로 parameter를 받을 경우 불필요하게 데이터베이스를 한번 더 조회해야하는 문제가 발생했습니다.  
따라서 해당 부분을 해결하고자 parameter를 변경했습니다. 
그 부분에 대해서 봐주시면 감사합니다.
---
기존 테스트 코드 수정 완료했습니다. 
---
> refactor : diary 관련 request Parameter memberId -> coupleId 변경

- api/src/main/java/com/lovely4k/backend/couple/controller/CoupleController.java
- api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
- api/src/main/java/com/lovely4k/backend/couple/service/response/CoupleProfileGetResponse.java
- api/src/main/java/com/lovely4k/backend/member/controller/request/MemberProfileEditRequest.java
- api/src/main/java/com/lovely4k/backend/member/service/MemberService.java
- api/src/main/java/com/lovely4k/backend/member/service/request/MemberProfileEditServiceRequest.java
- api/src/main/java/com/lovely4k/backend/member/service/response/MemberProfileGetResponse.java
- api/src/main/resources/schema/schema.sql
- api/src/test/java/com/lovely4k/backend/couple/controller/CoupleControllerTest.java
- api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceTest.java
- api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
- api/src/test/java/com/lovely4k/backend/diary/service/request/DiaryCreateRequestTest.java
- api/src/test/java/com/lovely4k/backend/member/controller/MemberControllerTest.java
- api/src/test/java/com/lovely4k/backend/member/service/MemberServiceTest.java
- api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
- api/src/test/java/com/lovely4k/docs/member/MemberControllerDocsTest.java
- model/src/main/java/com/lovely4k/backend/couple/Couple.java
- model/src/main/java/com/lovely4k/backend/diary/Diary.java
- model/src/main/java/com/lovely4k/backend/member/Member.java
- model/src/test/java/com/lovely4k/backend/couple/CoupleTest.java
- model/src/test/java/com/lovely4k/backend/diary/DiaryTest.java
- model/src/test/java/com/lovely4k/backend/member/MemberTest.java
- 커플 엔티티 생성의 책임을 service에서 Couple 객체로 넘겨주었습니다.
- 회원 수정 시 변경되지 않는 requestDTO에서 sex필드를 제거하였습니다.
---
- 없습니다.
---
---
- 테스트 완료하였습니다.
---
> refactor : 코드 리뷰 반영

- api/src/main/java/com/lovely4k/backend/couple/controller/CoupleController.java
- api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
- api/src/main/java/com/lovely4k/backend/couple/service/response/CoupleProfileGetResponse.java
- api/src/main/java/com/lovely4k/backend/member/controller/request/MemberProfileEditRequest.java
- api/src/main/java/com/lovely4k/backend/member/service/request/MemberProfileEditServiceRequest.java
- api/src/main/java/com/lovely4k/backend/member/service/response/MemberProfileGetResponse.java
- api/src/main/resources/schema/schema.sql
- api/src/test/java/com/lovely4k/backend/couple/controller/CoupleControllerTest.java
- api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceTest.java
- api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
- api/src/test/java/com/lovely4k/backend/diary/service/request/DiaryCreateRequestTest.java
- api/src/test/java/com/lovely4k/backend/member/controller/MemberControllerTest.java
- api/src/test/java/com/lovely4k/backend/member/service/MemberServiceTest.java
- api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
- api/src/test/java/com/lovely4k/docs/member/MemberControllerDocsTest.java
- model/src/main/java/com/lovely4k/backend/couple/Couple.java
- model/src/main/java/com/lovely4k/backend/diary/Diary.java
- model/src/main/java/com/lovely4k/backend/member/Member.java
- model/src/test/java/com/lovely4k/backend/diary/DiaryTest.java
- 코드리뷰들을 반영하였습니다.
- Member엔티티의 sex 필드를 Enum으로 변경함에따라 다른 파일도 추가적인 수정을 하였습니다.
---
- 없습니다.
---
---
- 테스트 성공적으로 수행됩니다.
---
> refactor : pr 리뷰 반영(1차 스프린트)

- .gitignore
- api/src/main/java/com/lovely4k/backend/common/config/WebConfig.java
- api/src/main/resources/application-local.yaml
- api/src/main/resources/application.yaml
- api/src/main/resources/static/hello.html
- api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
- api/src/test/resources/application.yaml
- build.gradle
- model/src/test/resources/application.yaml
docs 관련 조회 할 수 없는 문제 발생 
yaml 일부 오류 발견
---
없습니다.
---
공통 해결
---
없습니다. 
---
> chore : yaml, docs 설정 변경

- api/src/main/java/com/lovely4k/backend/couple/service/response/CoupleProfileGetResponse.java
- api/src/main/java/com/lovely4k/backend/member/service/response/MemberProfileGetResponse.java
- api/src/test/java/com/lovely4k/backend/couple/controller/CoupleControllerTest.java
- api/src/test/java/com/lovely4k/backend/member/controller/MemberControllerTest.java
- api/src/test/java/com/lovely4k/backend/member/service/MemberServiceTest.java
- api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
- api/src/test/java/com/lovely4k/docs/member/MemberControllerDocsTest.java
- 프론트 측에서 커플 조회시 회원의 이미지 url을 추가적으로 요청하셔서 수정하였습니다.
- 회원 조회시 성별은 필요없다는 의견이 있어서 삭제하였습니다.
---
- 없습니다.
---
---
---
> refactor : 프론트 의견 반영

- api/build.gradle
- api/src/main/resources/application-prod1.yaml
- api/src/main/resources/application-prod2.yaml
- api/src/main/resources/application.yaml
- actuator 도입 -> 전반적인 모니터링을 위해 도입을 하게 되었습니다.
- yaml파일 분리 -> 공통 yaml을 보다 명확하게 관리하기 위해 prod관련 yaml을 분리했습니다.
---
없습니다.
---
포커스 부분은 없으나 credential에 actuator 관련 설정들이 추가되었습니다. 
해당 부분은 Slack으로 공유 드리도록 하겠습니다. 
---
---
> feat : prod 파일 분리 및 actuator 도입

- api/src/main/java/com/lovely4k/backend/common/imageuploader/AWSS3Uploader.java
이미지 업로드시 잘못된 url 반환하는 문제 해결
---
없습니다. 
---
없습니다.
---
테스트 완료
---
> refactor : AWS Image upload시 반환 url 변경

- api/build.gradle
> feat : prometheus 의존성 추가

- api/src/docs/asciidoc/api/diary/diary-create.adoc
- api/src/docs/asciidoc/api/login/login.adoc
- api/src/docs/asciidoc/api/question/questions.adoc
- api/src/docs/asciidoc/index.adoc
- api/src/main/java/com/lovely4k/backend/member/controller/MemberController.java
- scripts/start.sh
> docs : 로그인 docs 작성

- api/src/main/java/com/lovely4k/backend/couple/controller/CoupleController.java
- api/src/test/java/com/lovely4k/backend/couple/controller/CoupleControllerTest.java
- api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
> refactor : 커플 초대코드 발급 http 메소드 변경

- api/src/docs/asciidoc/api/diary/diary-delete.adoc
- api/src/docs/asciidoc/api/diary/diary-getDetail.adoc
- api/src/docs/asciidoc/api/member/member-profile-get.adoc
- api/src/main/java/com/lovely4k/backend/couple/controller/CoupleController.java
- api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
- api/src/main/java/com/lovely4k/backend/couple/service/response/CoupleProfileGetResponse.java
- api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
- api/src/test/java/com/lovely4k/backend/couple/controller/CoupleControllerTest.java
- api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceTest.java
- api/src/test/java/com/lovely4k/docs/RestDocsSupport.java
- api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
- api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
> refactor : api 문서 수정 및 커플 프로필 응답 변경

- .gitignore
- api/src/main/java/com/lovely4k/backend/common/GlobalExceptionHandler.java
- api/src/main/java/com/lovely4k/backend/common/log/HttpAspect.java
- api/src/main/java/com/lovely4k/backend/common/log/HttpLogResponse.java
- api/src/main/java/com/lovely4k/backend/common/log/PrepareStatementInspector.java
- api/src/main/java/com/lovely4k/backend/common/log/SqlLogConfig.java
- api/src/main/resources/application.yaml
- api/src/main/resources/logback-spring.xml
- api/src/test/java/com/lovely4k/backend/common/log/HttpAspectTest.java
- api/src/test/java/com/lovely4k/backend/couple/controller/CoupleControllerTest.java
---
---
- 로그백 설정을 했고 기존에 있던 sql 로그는 클래스로 구현했습니다.
- local에서는 콘솔 출력, prod1, prod2 프로필에서는 파일에 쓰도록 구현했습니다.
- 하루 지난 로그파일은 그 날짜 명으로 압축 되며 최대 30일 보관하고, 로그 파일이 5기가 넘을 경우 오래된 순으로 삭제하게 했습니다.
---
---
> feat : logback 설정 추가

- api/src/main/java/com/lovely4k/backend/calendar/controller/CalendarController.java
- api/src/main/java/com/lovely4k/backend/calendar/controller/request/CreateCalendarRequest.java
- api/src/main/java/com/lovely4k/backend/calendar/service/CalendarCommandService.java
- api/src/main/java/com/lovely4k/backend/calendar/service/request/CreateCalendarServiceReqeust.java
- api/src/main/java/com/lovely4k/backend/calendar/service/response/CreateCalendarResponse.java
- api/src/main/resources/application.yaml
- api/src/main/resources/schema/schema.sql
- api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
- api/src/test/java/com/lovely4k/backend/calendar/controller/CalendarControllerTest.java
- api/src/test/java/com/lovely4k/backend/calendar/service/CalendarCommandServiceTest.java
- api/src/test/java/com/lovely4k/docs/calendar/CalendarApiDocsTest.java
- api/src/test/resources/application.yaml
- model/src/main/java/com/lovely4k/backend/calendar/Calendar.java
- model/src/test/java/com/lovely4k/backend/calendar/CalendarTest.java
---
---
- 일정을 생성하는 기능이고 따로 특이사항은 없습니다.
---
---
> feat : calendar create

- api/src/main/java/com/lovely4k/backend/calendar/controller/CalendarController.java
- api/src/main/java/com/lovely4k/backend/calendar/controller/request/CreateCalendarRequest.java
- api/src/main/java/com/lovely4k/backend/calendar/controller/request/UpdateCalendarRequest.java
- api/src/main/java/com/lovely4k/backend/calendar/service/CalendarCommandService.java
- api/src/main/java/com/lovely4k/backend/calendar/service/request/CreateCalendarServiceReqeust.java
- api/src/main/java/com/lovely4k/backend/calendar/service/request/UpdateCalendarServiceRequest.java
- api/src/main/java/com/lovely4k/backend/calendar/service/response/CreateCalendarResponse.java
- api/src/main/java/com/lovely4k/backend/calendar/service/response/UpdateCalendarResponse.java
- api/src/main/resources/application.yaml
- api/src/main/resources/schema/schema.sql
- api/src/test/java/com/lovely4k/TestData.java
- api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
- api/src/test/java/com/lovely4k/backend/calendar/controller/CalendarControllerTest.java
- api/src/test/java/com/lovely4k/backend/calendar/service/CalendarCommandServiceTest.java
- api/src/test/java/com/lovely4k/docs/calendar/CalendarApiDocsTest.java
- api/src/test/resources/application.yaml
- model/src/main/java/com/lovely4k/backend/calendar/Calendar.java
- model/src/test/java/com/lovely4k/backend/calendar/CalendarTest.java
---
---
- 일정 변경 기능입니다. 특이사항은 따로 없습니다.
---
---
> feat : calendar update

- api/src/main/java/com/lovely4k/backend/calendar/controller/CalendarController.java
- api/src/main/java/com/lovely4k/backend/calendar/controller/request/CreateCalendarRequest.java
- api/src/main/java/com/lovely4k/backend/calendar/controller/request/UpdateCalendarRequest.java
- api/src/main/java/com/lovely4k/backend/calendar/service/CalendarCommandService.java
- api/src/main/java/com/lovely4k/backend/calendar/service/request/CreateCalendarServiceReqeust.java
- api/src/main/java/com/lovely4k/backend/calendar/service/request/UpdateCalendarServiceRequest.java
- api/src/main/java/com/lovely4k/backend/calendar/service/response/CreateCalendarResponse.java
- api/src/main/java/com/lovely4k/backend/calendar/service/response/UpdateCalendarResponse.java
- api/src/main/resources/application.yaml
- api/src/main/resources/schema/schema.sql
- api/src/test/java/com/lovely4k/TestData.java
- api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
- api/src/test/java/com/lovely4k/backend/calendar/controller/CalendarControllerTest.java
- api/src/test/java/com/lovely4k/backend/calendar/service/CalendarCommandServiceTest.java
- api/src/test/java/com/lovely4k/docs/calendar/CalendarApiDocsTest.java
- api/src/test/resources/application.yaml
- model/src/main/java/com/lovely4k/backend/calendar/Calendar.java
- model/src/test/java/com/lovely4k/backend/calendar/CalendarTest.java
---
---
- 일정을 삭제하는 기능입니다. 특이사항은 따로 없습니다.
---
---
> feat : calendar delete

- api/src/docs/asciidoc/api/calendar/calendars.adoc
- api/src/docs/asciidoc/api/question/questions.adoc
- api/src/docs/asciidoc/index.adoc
- api/src/main/java/com/lovely4k/backend/calendar/controller/CalendarController.java
- api/src/main/java/com/lovely4k/backend/calendar/controller/request/FindCalendarsWithDateRequest.java
- api/src/main/java/com/lovely4k/backend/calendar/service/CalendarQueryService.java
- api/src/test/java/com/lovely4k/backend/calendar/controller/CalendarControllerTest.java
- api/src/test/java/com/lovely4k/backend/calendar/service/CalendarCommandServiceTest.java
- api/src/test/java/com/lovely4k/backend/calendar/service/CalendarQueryServiceTest.java
- api/src/test/java/com/lovely4k/docs/calendar/CalendarApiDocsTest.java
- model/src/main/java/com/lovely4k/backend/calendar/Calendar.java
- model/src/main/java/com/lovely4k/backend/calendar/repository/CalendarQueryRepository.java
- model/src/main/java/com/lovely4k/backend/calendar/repository/FindCalendarsWithDateRepositoryRequest.java
- model/src/test/java/com/lovely4k/backend/calendar/repository/CalendarQueryRepositoryTest.java
---
---
- asciidoc 파일을 작성했습니다.
- pr 피드백 받은 부분을 개선했습니다.
- 몇가지 SessionUser로 적용되지 않았던 endpoint를 변경했습니다.
---
---
> docs : calendar asciidoc

- api/build.gradle
- api/src/docs/asciidoc/api/login/login.adoc
- api/src/main/resources/schema/schema.sql
> refactor : 2.2배포 관련 일부 코드 수정

- api/src/main/resources/logback-spring.xml
> fix : logback ec2 경로 수정

- api/src/main/java/com/lovely4k/backend/authentication/CustomSuccessHandler.java
- api/src/main/java/com/lovely4k/backend/authentication/SecurityConfig.java
- api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
- api/src/test/resources/application.yaml
소셜 로그인 후 redirect 및 커플 재결합 요청 관련 로직 변경했습니다. 
기존에는 customsuccesshandler를 Component로 등록하지 않고 사용했으나, 
추후 redirect-url 변경점을 용이하게 변경하기 위해 @Value 어노테이션을 사용하면서 Component로 등록했고 SecurityConfig에서 
DI를 통해 주입받도록 로직을 변경했습니다. 
CustomSuccesshandler를 Component로 등록함에 따라 TestSupport class에 @MockBean 처리해 주었으며, test yaml에 관련 값을 mocking해두었습니다. 
redirect-url은 slack을 통해서 알려드리도록 하겠습니다. 
---
없습니다. 
---
변경 이유만 봐주시면 될 것 같습니다. 
---
없습니다. 
---
> refactor : 로그인 시 redirect url 변경 및 테스트 support code 추가

- api/src/main/java/com/lovely4k/backend/calendar/service/response/FindCalendarsWithDateServiceResponse.java
- api/src/main/java/com/lovely4k/backend/calendar/service/response/FindRecentCalendarsServiceResponse.java
- api/src/main/java/com/lovely4k/backend/question/controller/QuestionController.java
- api/src/main/java/com/lovely4k/backend/question/controller/request/AnsweredQuestionParamRequest.java
- api/src/main/resources/schema/schema.sql
- api/src/test/java/com/lovely4k/backend/calendar/service/CalendarQueryServiceTest.java
- api/src/test/java/com/lovely4k/docs/calendar/CalendarApiDocsTest.java
- model/src/main/java/com/lovely4k/backend/calendar/Calendar.java
- model/src/main/java/com/lovely4k/backend/calendar/repository/CalendarQueryRepository.java
- model/src/main/java/com/lovely4k/backend/calendar/repository/response/FindCalendarsWithDateResponse.java
- model/src/main/java/com/lovely4k/backend/calendar/repository/response/FindRecentCalendarsResponse.java
- model/src/test/java/com/lovely4k/backend/calendar/repository/CalendarQueryRepositoryTest.java
- model/src/test/resources/calendar.sql
---
---
- calendar 응답 필드에 ownerId를 추가했습니다.
- 답변한 질문을 조회하는 엔드포인트에서 아직 쿼리 파라미터로 coupleid를 받고 있는 부분을 session 기반으로 수정했습니다.
---
---
> refactor : calendar 응답 필드 ownerId 추가, question session으로부터 정보 얻어오기 추가

- .gitignore
- api/src/main/java/com/lovely4k/backend/common/log/HttpLogResponse.java
---
---
- 로그 포맷팅을 loki에 맞게 다시 작성했습니다.
---
---
> refactor : 로그 포맷팅 변경

- api/src/docs/asciidoc/api/question/questions.adoc
- api/src/main/java/com/lovely4k/backend/question/controller/QuestionController.java
- api/src/main/java/com/lovely4k/backend/question/service/QuestionQueryService.java
- api/src/test/java/com/lovely4k/backend/question/controller/QuestionControllerTest.java
- api/src/test/java/com/lovely4k/backend/question/service/QuestionQueryServiceForGameTest.java
- api/src/test/java/com/lovely4k/docs/question/QuestionApiDocsTest.java
- model/src/main/java/com/lovely4k/backend/question/repository/QuestionQueryRepository.java
- model/src/main/java/com/lovely4k/backend/question/repository/response/QuestionGameResponse.java
- model/src/test/resources/questions/findQuestionGame.sql
- 게임을 할 경우 질문을 랜덤 조회하는 기능입니다.
- 남,여 모두 답변한 질문에 한해서 조회가 가능합니다. 
- restdocs 작성하였습니다.
- 도연님이 작성하신 QuestionQueryService는 Moking을 통한 테스트이고 저는 Service계층 테스트는 통합테스트를 선호하여 QuestionQueryServiceForGameTest를 따로 만들어 작성하였습니다.
---
- 없습니다.
---
변경 이유에 작성한 내용들을 바탕으로 리뷰 부탁드립니다~!🙏
---
- 테스트 완료하였습니다.
---
> feat : game을 시작할 경우 랜덤 질문 조회 기능 구현[#113]

- api/src/main/java/com/lovely4k/backend/diary/controller/DiaryController.java
BaseTimeEntity 필드명 변경에 따른 @PageableDefault sort 인자명 변경했습니다. 
---
없습니다. 
---
변수명 변경이라 크게 봐야할 것은 없을 것 같습니다. 
---
---
> refactor : diary 목록 조회시 sort 변수명 변경

- api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceTest.java
- model/src/main/java/com/lovely4k/backend/couple/repository/CoupleQueryRepository.java
- 동성 커플일 경우 my, opponent가 모두 본인의 정보를 조회하는 상황이 발생하여 수정하였습니다.
- 동성 커플일 경우의 테스트 코드 추가로 작성하였습니다.
---
- 없습니다.
---
- 쿼리문 수정된것과 테스트 코드 확인 부탁드립니다!
---
- 테스트 완료하였습니다.
---
> refactor : 동성 커플일 경우 프로필 조회를 위한 쿼리 수정

- README.md
- api/src/main/java/com/lovely4k/backend/diary/controller/DiaryController.java
- api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceTest.java
- etc/index.html
- model/src/main/java/com/lovely4k/backend/couple/repository/CoupleQueryRepository.java
> Release 2.5

- api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryListResponse.java
- api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
프론트 측의 요청으로 인한 응답 변경 
---
없습니다. 
---
변경 포인트가 적어 따로 없습니다. 
---
---
> refactor : diary 목록 조회시 응답 목록 변경

- api/src/main/java/com/lovely4k/backend/calendar/service/response/FindRecentCalendarsServiceResponse.java
---
---
- 프론트엔드 요구사항에 맞춰 최근 일정 조회시 데이터가 없으면 빈 객체를 반환하도록 했습니다.
---
---
> refactor : 최근 일정 조회 없을 시 빈객체 주기(프론트 요구사항 반영)

- api/build.gradle
- api/src/docs/asciidoc/index.adoc
- api/src/main/java/com/lovely4k/backend/diary/controller/DiaryController.java
- api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
- api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryDetailResponse.java
- api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryListByMarkerResponse.java
- api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
- api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
- model/src/main/java/com/lovely4k/backend/member/Sex.java
현재 사용하지 않는 의존성이 있어 제거 했습니다.
- session-jdbc 제거
프론트 측 요구사항에 따른 API 응답 변경했습니다. 
- 모든 조회 로직에서 placeName, latitude, longitude 추가
---
없습니다. 
---
변경 포인트가 적어 전체적으로 봐주시면 좋을 것 같습니다.
---
변경사항에 따른 테스트 완료
---
> refactor : diary

- api/src/main/java/com/lovely4k/backend/common/log/HttpLogResponse.java
> refactor : form-data가 쿼리 파라미터에 들어가기 때문에 로그 포맷팅 형식 변경

- api/src/main/java/com/lovely4k/backend/common/log/HttpLogResponse.java
> release 2.7

- api/src/main/java/com/lovely4k/backend/common/log/HttpLogResponse.java
---
---
- 이전에 합쳤던 로그 포맷팅이 약간 오류가 있어서 다시 작성했습니다. 로컬 대시보드에서 확인했으니 괜찮을 겁니다 감사합니다.
---
---
> refactor : 로그 포맷팅 형식 재변경

- api/src/main/java/com/lovely4k/backend/diary/controller/DiaryController.java
- api/src/main/java/com/lovely4k/backend/diary/controller/request/WebDiaryEditRequest.java
- api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
- api/src/main/java/com/lovely4k/backend/diary/service/request/DiaryEditRequest.java
- api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
- api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
- api/src/test/java/com/lovely4k/docs/diary/MockDiaryEditRequest.java
- model/src/main/java/com/lovely4k/backend/diary/Diary.java
- model/src/test/java/com/lovely4k/backend/diary/DiaryTest.java
front 요구사항 반영하여 코드를 일부 변경했습니다. 
추가적으로 동성으로 커플을 맺을 경우에도 개개인의 성별이 바뀌지 않는 부분을 간과하여 상세조회시 로직을 조금 변경했습니다.
---
없습니다.
---
변경된 포인트 위주로 Service, Domain 로직봐주시면 좋을 것 같아요.
---
---
> refactor : front 요구사항 반영

- api/src/docs/asciidoc/api/couple/couple-delete.adoc
- api/src/docs/asciidoc/api/couple/couple-recouple.adoc
- api/src/docs/asciidoc/index.adoc
- api/src/main/java/com/lovely4k/backend/couple/controller/CoupleController.java
- api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
커플 복원 / 끊기 관련해 문서 작성했습니다. 
> 부가적으로 문서에 queryParameter가 아직 있어 해당 부분 수정했습니다. 
---
없습니다. 
---
문서 관련 수정이라 별다르게 봐야할 부분은 없을 것 같습니다. 
---
---
> docs : 커플 복원 / 끊기 관련 api 문서 작성

- api/src/main/java/com/lovely4k/backend/authentication/token/SecurityConfig.java
- api/src/main/java/com/lovely4k/backend/calendar/controller/CalendarController.java
- api/src/main/java/com/lovely4k/backend/calendar/service/CalendarQueryService.java
- api/src/main/java/com/lovely4k/backend/calendar/service/response/FindCalendarsWithDateServiceResponse.java
- api/src/main/java/com/lovely4k/backend/calendar/service/response/FindRecentCalendarsServiceResponse.java
- api/src/main/java/com/lovely4k/backend/common/config/WebConfig.java
- api/src/main/java/com/lovely4k/backend/question/controller/request/AnsweredQuestionParamRequest.java
- api/src/test/java/com/lovely4k/backend/calendar/service/CalendarQueryServiceTest.java
- api/src/test/java/com/lovely4k/docs/calendar/CalendarApiDocsTest.java
- model/src/main/java/com/lovely4k/backend/calendar/repository/CalendarQueryRepository.java
- model/src/main/java/com/lovely4k/backend/calendar/repository/response/FindCalendarsWithDateResponse.java
- model/src/main/java/com/lovely4k/backend/calendar/repository/response/FindRecentCalendarsResponse.java
- model/src/test/java/com/lovely4k/backend/calendar/repository/CalendarQueryRepositoryTest.java
---
---
- 요구사항에 맞춰 calendar 응답에 대해 남자, 여자가 아닌 my, opponent로 구분지어서 응답했습니다. 이외 특이사항 없습니다.
---
---
> refactor : calendar 응답 boy, girl이 아닌 my, opponent로 변경

- api/src/main/java/com/lovely4k/backend/common/imageuploader/AWSS3Uploader.java
- api/src/main/java/com/lovely4k/backend/diary/service/DiaryImageUploader.java
- api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
- api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryListResponse.java
- api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
- api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
- api/src/test/resources/application.yaml
두가지 변경사항이 있습니다.
- 다이어리 목록 조회 변경
- 프론트 분들의 API응답 변경 요구사항으로 인한 변경
- 다이어리 생성 및 수정 시 기본 이미지 설정
- 기존의 경우 사진을 업로드하지 않으면 아무것도 안들어갔었습니다. 
- 그러한 것 보다는 서비스에서 제공하는 이미지를 넣으면 좋을 것 같아 추가적으로 로직을 작성했습니다. 
- 이에 따라 기본 이미지가 삭제되지 않도록 로직을 조금 추가했습니다. 
---
없습니다.
---
이미지 업로드 관련한 로직에 초점을 두고 봐주시면 좋을 것 같습니다.
---
---
> Refactor diary

- api/src/docs/asciidoc/api/couple/couple-delete.adoc
- api/src/docs/asciidoc/api/couple/couple-recouple.adoc
- api/src/docs/asciidoc/index.adoc
- api/src/main/java/com/lovely4k/backend/authentication/token/SecurityConfig.java
- api/src/main/java/com/lovely4k/backend/calendar/controller/CalendarController.java
- api/src/main/java/com/lovely4k/backend/calendar/service/CalendarQueryService.java
- api/src/main/java/com/lovely4k/backend/calendar/service/response/FindCalendarsWithDateServiceResponse.java
- api/src/main/java/com/lovely4k/backend/calendar/service/response/FindRecentCalendarsServiceResponse.java
- api/src/main/java/com/lovely4k/backend/common/config/WebConfig.java
- api/src/main/java/com/lovely4k/backend/common/imageuploader/AWSS3Uploader.java
- api/src/main/java/com/lovely4k/backend/couple/controller/CoupleController.java
- api/src/main/java/com/lovely4k/backend/diary/service/DiaryImageUploader.java
- api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
- api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryListResponse.java
- api/src/main/java/com/lovely4k/backend/question/controller/request/AnsweredQuestionParamRequest.java
- api/src/test/java/com/lovely4k/backend/calendar/service/CalendarQueryServiceTest.java
- api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
- api/src/test/java/com/lovely4k/docs/calendar/CalendarApiDocsTest.java
- api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
- api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
- api/src/test/resources/application.yaml
- model/src/main/java/com/lovely4k/backend/calendar/repository/CalendarQueryRepository.java
- model/src/main/java/com/lovely4k/backend/calendar/repository/response/FindCalendarsWithDateResponse.java
- model/src/main/java/com/lovely4k/backend/calendar/repository/response/FindRecentCalendarsResponse.java
- model/src/test/java/com/lovely4k/backend/calendar/repository/CalendarQueryRepositoryTest.java
> release-2.8

- api/src/docs/asciidoc/api/couple/couple-temperature.adoc
- api/src/docs/asciidoc/index.adoc
- api/src/main/java/com/lovely4k/backend/couple/controller/CoupleController.java
- api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
- api/src/main/java/com/lovely4k/backend/couple/service/response/CoupleTemperatureResponse.java
- api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceTest.java
- api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
사랑의 온도 조회 기능 추가하였습니다. 
---
없습니다.
---
단순한 조회 로직만 추가 된 것이라 전반적으로 봐 주시면 좋을 것 같습니다.
---
추가 기능에 따른 테스트 완료
---
> feat : 사랑의 온도 조회 기능 추가

- api/src/main/java/com/lovely4k/backend/common/sessionuser/LoginUserArgumentResolver.java
- api/src/main/java/com/lovely4k/backend/question/service/QuestionValidator.java
- api/src/main/resources/schema/schema.sql
- api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
- model/src/main/java/com/lovely4k/backend/question/repository/QuestionQueryRepository.java
- model/src/test/java/com/lovely4k/backend/question/repository/QuestionQueryRepositoryTest.java
---
---
- 조회 쿼리를 TIMESTAMPDIFF가 아닌 DATEDIFF 함수를 이용했습니다. 
- H2 DB는 이를 인식하지 못해서 disable 처리를 했습니다.
- 비 로그인 유저에 대한 예외를 처리했습니다.
---
---
> fix : question 조회시 시간을 제외하고 날짜만 비교해서 조회, 비로그인 예외 추가

- api/src/docs/asciidoc/api/couple/couple-delete.adoc
- api/src/docs/asciidoc/api/couple/couple-recouple.adoc
- api/src/main/java/com/lovely4k/backend/authentication/CustomSuccessHandler.java
- api/src/main/java/com/lovely4k/backend/couple/controller/CoupleController.java
- api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
커플 끊기, 복원 관련 end-point 변경하였습니다. 
기존에는 Path Variable로 받고 있었습니다. 
생각해보니 저희 서비스의 경우 로그인을 하지 않으면 서비스를 이용할 수 없기 때문에 Path Variable이 필요 없다는 판단을 했습니다. 
이에 따라 end-point 변경하였습니다. 
---
없습니다.
---
변경 포인트가 적어 전반적으로 봐주시면 좋을 것 같습니다.
---
docs 관련 테스트 코드 변경하였습니다
---
> refactor : 커플 끊기, 복원 관련 end-point 변경

- api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
- api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
- model/src/main/java/com/lovely4k/backend/member/Member.java
- model/src/main/java/com/lovely4k/backend/member/repository/MemberRepository.java
- model/src/main/java/com/lovely4k/backend/member/util/RandomUtils.java
- model/src/test/java/com/lovely4k/backend/couple/repository/CoupleQueryRepositoryTest.java
- model/src/test/java/com/lovely4k/backend/member/MemberTest.java
- model/src/test/java/com/lovely4k/backend/member/repository/MemberRepositoryTest.java
- 회의에 따라 커플이 맺어질 경우 소셜 로그인 시 받아오지 못하는 정보들에 대해서 임의로 저장해줍니다.
- birthday, mbti, calendar color
- 커플이 맺어질 경우 사용자의 Role을 `USER`로 변경해줍니다.
---
없습니다.
---
- 임의의 데이터를 주는것을 클래스 내부에 enum을 만들어서 구현해보았습니다.
- boy, girl을 두번 조회하는 부분은 쿼리 튜닝할때 수정하겠습니다.
---
테스트 완료하였습니다.
---
> 서비스 이용 정책 추가

- api/src/main/java/com/lovely4k/backend/authentication/token/JwtFilter.java
> Release 2.9.1

- api/src/main/java/com/lovely4k/backend/authentication/token/JwtFilter.java
> refactor : access토큰 응답 json 응답으로 변경

- api/src/docs/asciidoc/api/diary/diary-edit.adoc
- api/src/main/java/com/lovely4k/backend/diary/controller/request/WebDiaryEditRequest.java
- api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
- api/src/main/java/com/lovely4k/backend/diary/service/request/DiaryEditRequest.java
- api/src/test/java/com/lovely4k/backend/diary/controller/DiaryControllerTest.java
- api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
- api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
- api/src/test/java/com/lovely4k/docs/diary/MockDiaryEditRequest.java
- model/src/main/java/com/lovely4k/backend/diary/Diary.java
- model/src/test/java/com/lovely4k/backend/diary/DiaryTest.java
다이어리 수정 로직 변경했습니다. 
- 기존 
- 나, 상대방의 텍스트 수정 가능
- 변경 후 
- 나의 텍스트만 수정 가능 
---
없습니다. 
---
서비스와 도메인 코드 중점적으로 봐주시면 좋을 것 같아요
---
명세 변경에 따른 테스트 코드 변경 
---
> refactor : 다이어리 수정 로직 변경

- api/src/main/java/com/lovely4k/backend/calendar/controller/CalendarController.java
- api/src/main/java/com/lovely4k/backend/calendar/service/CalendarCommandService.java
- api/src/test/java/com/lovely4k/backend/calendar/service/CalendarCommandServiceTest.java
- api/src/test/java/com/lovely4k/docs/calendar/CalendarApiDocsTest.java
- model/src/main/java/com/lovely4k/backend/calendar/Calendar.java
- model/src/main/java/com/lovely4k/backend/diary/QDiaryRepository.java
- model/src/test/java/com/lovely4k/backend/calendar/CalendarTest.java
> Release 3.0

- model/src/main/java/com/lovely4k/backend/diary/DiaryRepository.java
쿼리 튜닝을 하면서 잘못된 문법으로 비교를 하여 해당 부분 쿼리 수정했습니다.
---
없습니다 
---
변경 사항이 극히 적어서 쿼리만 보시면 될 것 같습니다. 
---
---
> refactor: 다이어리 지도 조회시 쿼리 수정

- model/src/main/java/com/lovely4k/backend/member/Member.java
- model/src/main/java/com/lovely4k/backend/member/util/MemberRandomUtils.java
- 임의로 설정해둔 색상 코드를 변경해주었습니다.
---
- 없습니다.
---
없습니다.
---
테스트 완료하였습니다.
---
> fix : 랜덤 색상 hexcode 수정

- api/src/main/java/com/lovely4k/backend/common/error/GlobalExceptionHandler.java
- api/src/main/java/com/lovely4k/backend/common/error/exception/QuestionCreateCountExceedException.java
- api/src/main/java/com/lovely4k/backend/question/exception/QuestionCreateCountExceedException.java
- api/src/main/java/com/lovely4k/backend/question/service/QuestionValidator.java
- api/src/test/java/com/lovely4k/backend/question/service/QuestionValidatorTest.java
> refactor : 요구사항에 맞춰 오늘의 질문 생성 예외 발생시 200으로 응답

- api/build.gradle
- api/src/main/java/com/lovely4k/backend/common/imageuploader/AWSS3Uploader.java
- api/src/main/java/com/lovely4k/backend/common/imageuploader/ImageResizer.java
- api/src/main/java/com/lovely4k/backend/common/imageuploader/ResizedMultipartFile.java
- api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
- api/src/main/resources/application-local.yaml
- api/src/test/java/com/lovely4k/backend/IntegrationTestSupport.java
- api/src/test/java/com/lovely4k/backend/couple/IncreaseTemperatureEventHandlerTest.java
- api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceConcurrencyTest.java
---
---
- 이미지 업로드 기능을 최적화 했습니다.
- 주석과 앞서 작성한 문서를 참고하시면 이해가 쉬울 것입니다.
- 삭제시에는 병렬 스트림을 사용했습니다.
---
---
> refactor : 이미지 처리 최적화(리사이징, 병렬 처리)

- api/build.gradle
- api/src/main/java/com/lovely4k/backend/calendar/service/CalendarCommandService.java
- api/src/main/java/com/lovely4k/backend/calendar/service/CalendarQueryService.java
- api/src/main/java/com/lovely4k/backend/common/cache/CacheEvictedEvent.java
- api/src/main/java/com/lovely4k/backend/common/cache/CustomCacheManager.java
- api/src/main/java/com/lovely4k/backend/common/config/CacheConfig.java
- api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
- api/src/main/java/com/lovely4k/backend/diary/service/DiaryQueryService.java
- api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
- api/src/main/java/com/lovely4k/backend/member/service/MemberService.java
- api/src/main/java/com/lovely4k/backend/question/service/QuestionQueryService.java
- api/src/main/java/com/lovely4k/backend/question/service/QuestionService.java
- api/src/main/resources/application-local.yaml
---
---
- 캐시 설정을 추가했습니다.
---
---
> chore : 캐시 설정 추가

- api/src/main/java/com/lovely4k/backend/authentication/token/UserDetailsServiceImpl.java
- api/src/main/java/com/lovely4k/backend/calendar/service/CalendarCommandService.java
- api/src/main/java/com/lovely4k/backend/calendar/service/CalendarQueryService.java
- api/src/main/java/com/lovely4k/backend/common/cache/CacheConstants.java
- api/src/main/java/com/lovely4k/backend/common/config/CacheConfig.java
- api/src/main/java/com/lovely4k/backend/common/db/DatabaseType.java
- api/src/main/java/com/lovely4k/backend/common/db/RoutingDataSource.java
- api/src/main/java/com/lovely4k/backend/couple/IncreaseTemperatureEventHandler.java
- api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
- api/src/main/java/com/lovely4k/backend/diary/service/DiaryQueryService.java
- api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
- api/src/main/java/com/lovely4k/backend/member/event/MemberCreatedEventListener.java
- api/src/main/java/com/lovely4k/backend/member/service/MemberService.java
- api/src/main/java/com/lovely4k/backend/question/service/QuestionQueryService.java
- api/src/main/java/com/lovely4k/backend/question/service/QuestionService.java
- api/src/main/java/com/lovely4k/backend/question/service/QuestionServiceSupporter.java
- api/src/main/resources/application-local.yaml
- api/src/test/java/com/lovely4k/backend/member/event/MemberCreatedEventListenerTest.java
- api/src/test/java/com/lovely4k/backend/question/service/QuestionServiceTest.java
- build.gradle
- model/src/main/java/com/lovely4k/backend/member/event/MemberUpdatedEvent.java
- model/src/main/java/com/lovely4k/backend/question/repository/QuestionFormRepository.java
> Release 3.1

- README.md
> Release 3.2
